### ISSUE TITLE
Make Elasticsearch and S3 service names dynamic.

### ISSUE THREAD

**Issue by ozzyjohnson** [18F/open-data-maker#139]
**Background:**

Currently, both [elasticsearch](https://github.com/18F/open-data-maker/blob/213e1c78ac21ef4e82370032eac98357cdbee869/lib/data_magic.rb#L189) and [s3](https://github.com/18F/open-data-maker/blob/213e1c78ac21ef4e82370032eac98357cdbee869/lib/data_magic.rb#L42) use hardcoded names.

**Why:**

I'd like to see this change for a couple of reasons which are both in support of adding flexibility and resiliency to college-choice immediately and anything else built on open-data-maker going forward. 

**Benefits:**

1. Support [blue-green](http://docs.pivotal.io/pivotalcf/devguide/deploy-apps/blue-green.html) style service updates. This will enable out of band data loading fast reversion of previous data snapshots. I'd say this is essential and could be handled by defaulting to 'eservice' unless an ESERVICE_NAME environment variable is found.

2. Enable straightforward horizontal scaling of the backend elasticsearch. This bears more discussion as it would require more logic in the app. The idea would be to have 2 or more elasticsearch instances available to 2 or more API instances.

    Perhaps there's a straightforward to implement hash function that could take act on the [instance_index](http://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html#CF-INSTANCE-INDEX) against a list of bound elasticsearch instances?

    Otherwise, binding a user service that contains a map of instance indexes to services instances would seem a doable MVP.

**Comment by ultrasaurus** [comment]
@ozzyjohnson elasticsearch gets it's URI from CloudFoundry, likewise s3, but I was thinking of making a config.yml.  I assume you are talking about the non CF deploy?

**Comment by ozzyjohnson** [comment]
@ultrasaurus - Right, it gets the URI out of the service specified by the hardcoded service name `eservice` and `bservice`. It's that string, the service name, that I'd want to be able to specify. Otherwise, blue-green or similar deploy of the app would require multiple spaces as the app <-> space <-> service are welded together.

Being able to specify the URI directly for a non-CF deploy would great as well.

Having a `config.yml` would be nice. I'd want it to be able to specify a service name or a complete config.

**Comment by sephcoster** [comment]
Maybe this doesn't get to exactly what you're looking for, but [ES index aliasing](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html) may give you the flexibility you need to do your blue / green and also help with scaling / pointing to multiple indexes without having to mess around with environment variables.

**Comment by ultrasaurus** [comment]
@sephcoster thanks for the note and reference!  This issue refers to something really basic that we hard-code our elasticsearch reference to localhost, and likewise have bucketnames in the code, which is not awesome.

**Comment by ultrasaurus** [comment]
@ozzy first step of this is ready (in dev branch)
envirornment variables
- s3_bucket_service  (defaults to bservice if env var not set)
- es_service (defaults to eservice if env var not set)

**Comment by ozzyjohnson** [comment]
Wondefful. I'll have a look.
