### ISSUE TITLE
can't sort on nested field

### ISSUE THREAD

**Issue by ultrasaurus** [18F/open-data-maker#157]
on branch with new sample-data (dev-sample-data), go to: http://localhost:3000/cities?sort=area.water

```
[Failed to parse source [{\"from\":0,\"size\":20,\"query\":{\"match_all\":{}},\"sort\":[{\"area\":{\"order\":\"asc\"}},{\"water\":{\"order\":\"asc\"}}]}]]]; nested: SearchParseException[[development-city-data][4]: query[ConstantScore(*:*)],from[0],size[20]: Parse Failure [No mapping found for [area] in order to sort on]]; }]","status":400}
```

The issues is that this regex ```/(\w+):?(\w*)/```  given the string ```area.water``` will capture "area" and "water"

**Comment by ultrasaurus** [comment]
@yozlet @ridiculous gonna write a failing spec, but I'm a but mystified why ```:?``` seems to match ```.```

**Comment by ridiculous** [comment]
Oh right, didn't think about the nested fields. Changing it to `(\w+\.?\w*):?(\w*)` should fix it

**Comment by ultrasaurus** [comment]
@ridiculous what do I not understand about regex ```:?``` ?

**Comment by ultrasaurus** [comment]
also @ridiculous it can be deeply nested, like: one.two.three.four

**Comment by ultrasaurus** [comment]
this seems to work:  ```/(\w+[\.\w]*):?(\w*)/```

**Comment by ridiculous** [comment]
I think you probably understand it fine, it says zero or one colon. It's picking up `area.water` as separate fields because of how it's used with `scan`, which does a recursive matching.

To match multiple nested fields, we can change it to:
```ruby
([\w.]+):?(\w*)
```

I tested it here http://rubular.com/r/8E9IYsbXWr

**Comment by ultrasaurus** [comment]
@ridiculous I forgot that rubular does multiple matches.  For some reason I got caught up in the idea that there was some specialness to ```:```  -- thanks for chiming in with a quick response!

**Comment by ridiculous** [comment]
:+1:

**Comment by ultrasaurus** [comment]
PR merged!
