### ISSUE TITLE
API change: disambiguate option parameters from column/field parameters

### ISSUE THREAD

**Issue by yozlet** [18F/open-data-maker#176]
Before we freeze what we're calling the v1 API, we should deal with the ambiguity between options and field parameters in URLs. Our current option parameters are `fields`, `sort`, `zip`, `distance`, `page` and `per_page`. Given that Open Data Maker is intended to be a general purpose data search tool, we should avoid option names clashing with potential column names.

**Option prefix:** Prefix option parameters with a special character, such as an underscore or dollar sign (which is what [Socrata does](http://dev.socrata.com/docs/queries.html)). For example: `$fields=id,school.name&$page=3` (I'd prefer `$` over `_` because we're using underscore-prefixing elsewhere for a very different purpose, namely lowercased versions of searchable names)

**Move column parameters into options:** Create a `filter` or `where` option with a column name as part of the parameter name. For example, `school.zip=43563` would become `filter[school.zip]=43563`

I'm currently inclined towards the first idea - option prefixing - since it's a less radical change and keeps the URLs a little shorter, but I'm eager to hear other arguments and suggestions. However, we do need to make this change in the next couple of days.

/cc @ultrasaurus @shawnbot @slhaines @siruguri @diego-

**Comment by yozlet** [comment]
Addendum: @shawnbot said in chat that `_` would be easier to use than `$` to avoid URL-encoding.

**Comment by ultrasaurus** [comment]
also, seems easy to remember that _ shouldn't end up as part of the results... tho it will be used for two internal purposes

**Comment by yozlet** [comment]
OK, going with `_`. Thanks everyone!

**Comment by ultrasaurus** [comment]
fixed with https://github.com/18F/open-data-maker/pull/184
