### ISSUE TITLE
MOAR API DOCS

### ISSUE THREAD

**Issue by ultrasaurus** [18F/open-data-maker#199]
need to add the following sections to API.md

**Comment by ultrasaurus** [comment]
@yozlet did another PR with more documentation.  I didn't have any idea for what you mean by "Considerations when using the api.data.gov proxy"

**Comment by yozlet** [comment]
I can take the rest of this. What I meant by api.data.gov considerations was simply providing the API key in the URL, but I'll leave that for the moment.

**Comment by diego-** [comment]
FYI I sent a link to API.md to the beta group as part of a broader notice
about the prod API.

On Sep 9, 2015, at 6:49 PM, Yoz Grahame <notifications@github.com> wrote:

I can take the rest of this. What I meant by api.data.gov considerations
was simply providing the API key in the URL, but I'll leave that for the
moment.

—
Reply to this email directly or view it on GitHub
<https://github.com/18F/open-data-maker/issues/199#issuecomment-139066031>.

**Comment by yozlet** [comment]
Fixed by #193 and #201.
