### ISSUE TITLE
latest ElasticSearch version seems to be incompatible

### ISSUE THREAD

**Issue by sophiez2628** [18F/open-data-maker#238]
1.7.x seems to be the version that works with open data maker 

READ ME should have instructions for installing older versions of elastic search, just in case the bootstrap script does not work.

**Comment by ultrasaurus** [comment]
README refers to INSTALL.md -- fixed there, I think!

**Comment by yozlet** [comment]
Closing this in favour of a new tracking issue at #248. Thank you for reporting this, @sophiez2628!
