### ISSUE TITLE
Importer won't find data.yaml if there are too many files in the S3 bucket

### ISSUE THREAD

**Issue by yozlet** [18F/open-data-maker#250]
When `DataMagic::Config` looks for `data.yaml` it grabs the list of files in the S3 bucket and searches it for the filename. However, `@s3.list_objects()` only returns 1000 objects at a time, and if there are over 1000 objects in the bucket (because of backups/snapshots) then `data.yaml` won't be in that list and won't be loaded.

I suspect the best solution here is to not rely on file listing, and instead just assume that `data.yaml` is there and try to read it, taking an alternate path if that fails.

**Comment by dnesting** [comment]
+1 to "just try to do the thing" and not "see if we think the thing will work, and then try it" as a general rule.
