### ISSUE TITLE
Use ElasticSearch bulk import to speed up indexing

### ISSUE THREAD

**Issue by yozlet** [18F/open-data-maker#263]
https://www.elastic.co/guide/en/elasticsearch/reference/1.4/docs-bulk.html
http://www.rubydoc.info/gems/elasticsearch-api/Elasticsearch/API/Actions#bulk-instance_method

related:  
- Bulk insert https://github.com/18F/open-data-maker/pull/86

**Comment by pkarman** [comment]
after some profiling, I do not think ES bulk import would improve the ES speed. 80% of indexing time is spent in marshaling the CSV data.

See #295
