### ISSUE TITLE
Read CSVs in chunks using smarter_csv

### ISSUE THREAD

**Issue by ultrasaurus** [18F/open-data-maker#293]
We should consider this PR:  https://github.com/18F/open-data-maker/pull/94

**Comment by pkarman** [comment]
Also this: http://xjlin0.github.io/tech/2015/05/25/faster-parsing-csv-with-parallel-processing/

**Comment by pkarman** [comment]
#295 implements this

**Comment by yozlet** [comment]
Ultimately implemented & merged in #297.
