### ISSUE TITLE
As a data analyst, I would like to get the data as a csv, rather than json

### ISSUE THREAD

**Issue by ultrasaurus** [18F/open-data-maker#48]
the API should support whatever.json and whatever.csv 
csv should ignore pagination args, since that doesn't really make sense to the humans

**Comment by ange3** [comment]
Angela and Cameron are working on this issue.

**Comment by ultrasaurus** [comment]
started working on this here:  https://github.com/18F/open-data-maker/pull/79

**Comment by ultrasaurus** [comment]
@pablokang might be able to help with this

the PR above is probably not really helpful, except maybe the test

**Comment by ultrasaurus** [comment]
@cantino and @salogel42 will look at this

**Comment by ultrasaurus** [comment]
@salogel42 looks like there's a lot of good work here: https://github.com/salogel42/open-data-maker/commits/csv-export -- what's left to do before a pull request?

**Comment by ultrasaurus** [comment]
closing since the PR was merged -- thanks @cantino and @salogel42
