### ISSUE TITLE
When I search for New York, I shouldn't get New Hampshire

### ISSUE THREAD

**Issue by ultrasaurus** [18F/open-data-maker#53]
It's currently doing a text search where similar "relevant" documents are found, but that doesn't make sense for proper names like these. 

If I searched for "New" I would expect New York and New Hampshire, etc., but searching for New York (in a list of states) should just produce New York.

**Comment by ultrasaurus** [comment]
query_string might be what we are looking for:  https://gist.github.com/acreeger/1027916

**Comment by ultrasaurus** [comment]
here are the elasticsearch docs for query_string: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html

**Comment by rachelcolby11** [comment]
To address this bug, we changed the operator by nesting the query like this:

```Ruby
full_query = {
      index: 'development-city-data',
      body: {
        query: {
          match: { 
            name: {
              query: 'New York',
              operator: 'and'
            }
          }
        }
      }
    }
```

**Comment by aneyzberg** [comment]
working on this

**Comment by ultrasaurus** [comment]
fixed with: https://github.com/18F/open-data-maker/pull/141
