### ISSUE TITLE
when a csv has a byte order mark (BOM), it shouldn't be included as part of the column name

### ISSUE THREAD

**Issue by ultrasaurus** [18F/open-data-maker#81]
failing spec here:  https://github.com/18F/open-data-maker/tree/bom

**Comment by Karla-Isabel-Sandoval** [comment]
Caleb and I would  like to work on this issue.

**Comment by ultrasaurus** [comment]
Some progress here:  https://github.com/18F/open-data-maker/pull/130
adding Help Wanted tag again since this didn't get done at open source pairing event and someone else might want to pick it up

**Comment by yozlet** [comment]
Am having a poke at #130 now.

**Comment by ultrasaurus** [comment]
resolved https://github.com/18F/open-data-maker/pull/153
