### ISSUE TITLE
DATA_PATH should not be required to be set

### ISSUE THREAD

**Issue by siruguri** [18F/open-data-maker#83]
Not sure if I did something wrong but in the installation guide, it didn't say to set `DATA_PATH` to anything, but when I ran `rake import` without having set that variable I get this error:

````
rake aborted!
Elasticsearch::Transport::Transport::Errors::NotFound: [404] {"error":"IndexMissingException[[development-city-data] missing]","status":404}
/Users/sameer/.rvm/gems/ruby-2.2.2@global/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:135:in `__raise_transport_error'
/Users/sameer/.rvm/gems/ruby-2.2.2@global/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:227:in `perform_request'
/Users/sameer/.rvm/gems/ruby-2.2.2@global/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/Users/sameer/.rvm/gems/ruby-2.2.2@global/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/client.rb:119:in `perform_request'
/Users/sameer/.rvm/gems/ruby-2.2.2@global/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
/Users/sameer/.rvm/gems/ruby-2.2.2@global/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/actions/indices/delete.rb:44:in `delete'
/Users/sameer/.rvm/gems/ruby-2.2.2@global/gems/stretchy-0.4.6/lib/stretchy/utils/client_actions.rb:81:in `delete'
/Users/sameer/code/rails/open-data-maker/lib/data_magic/index.rb:76:in `import_with_dictionary'
tasks/import.rake:9:in `block in <top (required)>'
Tasks: TOP => import

````
When I exported `DATA_PATH` to point to `./sample_data`, everything worked smoothly.

Happy to submit a PR with that sentence added somewhere in the installation guide, if that's the right idea.

**Comment by ultrasaurus** [comment]
We're supposed to have ./sample-data as the default.  If you want to submit a PR that fixes that, it would be most welcome!

**Comment by siruguri** [comment]
hold on, I think I know what happened.

https://github.com/18F/open-data-maker/commit/bdfe9560dbb66959e8809b33de596adc86b512cf

caused the _first run_ of `rake import` to fail because it deletes an index
that doesn't exist.

So should this issue in fact be thus?

"Fail gracefully during import when index doesn't exist"

If that's right, I'll submit that PR.

**Comment by ultrasaurus** [comment]
@siruguri good catch.  Tho I think now that https://github.com/18F/open-data-maker/pull/84 is on track we want to re-index rather than deleting the index (and set sample-data to have unique key).  Then we could just check if the index exists and only create it if it doesn't (which is actually what DataMagic.create_index does).   

So, I *think* you could fix the bug by just calling DataMagic.create_index instead of client.indices.create (which we'll want to do anyways soon since I'm working on adding types), and *not* deleting...  

extra credit if you can come up with a failing test before the fix, but good to have the fix in any case

**Comment by ultrasaurus** [comment]
by the way: if you work on this, brannch from 'staging' since there's a lot of new stuff there that hasn't made it to master!

**Comment by ultrasaurus** [comment]
update: I started a dev branch and made it the default branch, if you haven't started, branch from there!

**Comment by ultrasaurus** [comment]
this is fixed in 'dev' branch  (create_index fails gracefully if you already have an index)
